name: docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
     - cron: "0 0 * * 1"
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          mpadge/pkgcheck:latest
          ghcr.io/ropensci-review-tools/pkgcheck:latest
    
    - name: Trigger pkgcheck-action build
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.RRT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'ropensci-review-tools',
            repo: 'pkgcheck-action',
            workflow_id: 'publish.yaml',
            ref: 'main'
          });
